site_name: PROJETO INTEGRADOR I
site_url: https://fcte-pi1.github.io/2025.2_PI1_Grupo02_Ajax/

markdown_extensions:
  - tables
  - md_in_html

nav:
  - Home:
      - Sobre: index.md
  - Arquitetura do hardware:
      - Diagrama de blocos: arquitetura/blocos.md
  - Testes:
      - 1. Estrutura do Roteiro: roteiro_testes/01-estrutura-do-roteiro.md
      - 2. Testes de Estrutura e Mecânica: roteiro_testes/02-testes-estrutura-mecanica.md
      - 3. Testes de Hardware: roteiro_testes/03-testes-hardware.md
      - 4. Testes de Software: roteiro_testes/04-testes-software.md
      - 5. Testes de Integração: roteiro_testes/05-testes-integracao.md
      - 6. Testes de Desempenho e Energia: roteiro_testes/06-testes-desempenho-energia.md
      - 7. Testes de Interface e Usabilidade: roteiro_testes/07-testes-interface-usabilidade.md
      - 8. Testes de Sistema: roteiro_testes/08-testes-sistema.md
      - 9. Critérios de Aceite: roteiro_testes/09-criterios-aceite.md
theme:
  logo: assets/LogoCadUn.png
  name: material
  font:
    text: IBM Plex Serif
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
  palette:
    - scheme: light
      primary: custom
      toggle:
        icon: material/weather-night
        name: Trocar para modo escuro

    - scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Trocar para modo claro
icon:
  repo: fontawesome/brands/git-alt

extra_css:
  - assets/css/custom.css