site_name: PROJETO INTEGRADOR I
site_url: https://fcte-pi1.github.io/2025.2_PI1_Grupo02_Ajax/

markdown_extensions:
  - tables
  - md_in_html

nav:
  - Home:
      - Sobre: index.md
  - Another tab example:
      - Test: ho.md
  - Guia de contribuição:
      - Fluxo de Trabalho (Git)': 'politica-de-contribuicao.md'
theme:
  logo: assets/LogoCadUn.png
  name: material
  font:
    text: IBM Plex Serif
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
  palette:
    - scheme: light
      primary: custom
      toggle:
        icon: material/weather-night
        name: Trocar para modo escuro

    - scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Trocar para modo claro
icon:
  repo: fontawesome/brands/git-alt

extra_css:
  - assets/css/custom.css
